services:
  - type: web
    name: university-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: JWT_SECRET
        generateValue: true
      - key: ALGORITHM
        value: HS256
